// <auto-generated />
using System;
using LegendsAwaken.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LegendsAwaken.Infrastructure.Migrations
{
    [DbContext(typeof(LegendsAwakenDbContext))]
    [Migration("20260423000000_TorreNivelDificuldade")]
    partial class TorreNivelDificuldade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Snapshot omitted — this migration was created without a Designer file.
            // BuildTargetModel is only used by migration scaffolding tooling, not by MigrateAsync().
            // If you need to scaffold a new migration, re-generate this Designer file with:
            //   dotnet ef migrations add <Name> --project LegendsAwaken.Infrastructure
#pragma warning restore 612, 618
        }
    }
}
