// <auto-generated />
using System;
using LegendsAwaken.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LegendsAwaken.Infrastructure.Migrations
{
    [DbContext(typeof(LegendsAwakenDbContext))]
    [Migration("20260425173413_AddHeroTitulo")]
    partial class AddHeroTitulo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Auxiliares.HeroiAfinidadeElemental", b =>
                {
                    b.Property<Guid>("HeroiId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Elemento")
                        .HasColumnType("INTEGER");

                    b.HasKey("HeroiId", "Elemento");

                    b.ToTable("HeroisAfinidades");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Auxiliares.HeroiBonusAtributo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Atributo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("HeroiId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Origem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HeroiId");

                    b.ToTable("HeroiBonusAtributo");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Auxiliares.HeroiTag", b =>
                {
                    b.Property<Guid>("HeroiId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.HasKey("HeroiId", "Tag");

                    b.ToTable("HeroisTags");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Auxiliares.HeroiVinculo", b =>
                {
                    b.Property<Guid>("HeroiId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VinculadoId")
                        .HasColumnType("TEXT");

                    b.HasKey("HeroiId", "VinculadoId");

                    b.ToTable("HeroisVinculos");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Cidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CapacidadeMaxima")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Populacao")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UltimaColeta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimoSustentoEm")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Construcao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CidadeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaAtiva")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoPredio")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.ToTable("Construcao");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Fragmento.BiomHeroPool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BiomeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DropWeight")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EHeroPrincipal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("HeroiId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Raridade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BiomeId");

                    b.HasIndex("HeroiId");

                    b.ToTable("BiomHeroPools");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000001"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000001"),
                            DropWeight = 30,
                            EHeroPrincipal = true,
                            HeroiId = new Guid("a1000000-0000-0000-0000-000000000004"),
                            Raridade = 4
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000002"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000001"),
                            DropWeight = 70,
                            EHeroPrincipal = false,
                            HeroiId = new Guid("a1000000-0000-0000-0000-000000000009"),
                            Raridade = 4
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000003"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000002"),
                            DropWeight = 30,
                            EHeroPrincipal = true,
                            HeroiId = new Guid("a1000000-0000-0000-0000-000000000006"),
                            Raridade = 4
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000004"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000002"),
                            DropWeight = 70,
                            EHeroPrincipal = false,
                            HeroiId = new Guid("a1000000-0000-0000-0000-000000000005"),
                            Raridade = 4
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000005"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000003"),
                            DropWeight = 20,
                            EHeroPrincipal = true,
                            HeroiId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Raridade = 5
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000006"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000003"),
                            DropWeight = 45,
                            EHeroPrincipal = false,
                            HeroiId = new Guid("a1000000-0000-0000-0000-000000000007"),
                            Raridade = 4
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000007"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000003"),
                            DropWeight = 35,
                            EHeroPrincipal = false,
                            HeroiId = new Guid("a1000000-0000-0000-0000-000000000008"),
                            Raridade = 4
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000008"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000003"),
                            DropWeight = 10,
                            EHeroPrincipal = false,
                            HeroiId = new Guid("a1000000-0000-0000-0000-000000000003"),
                            Raridade = 5
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000001"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000001"),
                            DropWeight = 35,
                            EHeroPrincipal = true,
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000001"),
                            Raridade = 3
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000002"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000001"),
                            DropWeight = 35,
                            EHeroPrincipal = false,
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000002"),
                            Raridade = 3
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000003"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000001"),
                            DropWeight = 20,
                            EHeroPrincipal = false,
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000004"),
                            Raridade = 3
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000004"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000001"),
                            DropWeight = 10,
                            EHeroPrincipal = false,
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000005"),
                            Raridade = 4
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000005"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000002"),
                            DropWeight = 30,
                            EHeroPrincipal = true,
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000007"),
                            Raridade = 4
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000006"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000002"),
                            DropWeight = 30,
                            EHeroPrincipal = false,
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000009"),
                            Raridade = 4
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000007"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000002"),
                            DropWeight = 25,
                            EHeroPrincipal = false,
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000011"),
                            Raridade = 4
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000008"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000002"),
                            DropWeight = 15,
                            EHeroPrincipal = false,
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000012"),
                            Raridade = 4
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000009"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000003"),
                            DropWeight = 35,
                            EHeroPrincipal = true,
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000014"),
                            Raridade = 4
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000010"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000003"),
                            DropWeight = 30,
                            EHeroPrincipal = false,
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000015"),
                            Raridade = 4
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000011"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000003"),
                            DropWeight = 20,
                            EHeroPrincipal = false,
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000018"),
                            Raridade = 4
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000012"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000003"),
                            DropWeight = 15,
                            EHeroPrincipal = false,
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000017"),
                            Raridade = 5
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000013"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000004"),
                            DropWeight = 30,
                            EHeroPrincipal = true,
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000020"),
                            Raridade = 5
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000014"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000004"),
                            DropWeight = 30,
                            EHeroPrincipal = false,
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000021"),
                            Raridade = 4
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000015"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000004"),
                            DropWeight = 25,
                            EHeroPrincipal = false,
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000023"),
                            Raridade = 5
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000016"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000004"),
                            DropWeight = 15,
                            EHeroPrincipal = false,
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000022"),
                            Raridade = 5
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000017"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000005"),
                            DropWeight = 30,
                            EHeroPrincipal = true,
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000026"),
                            Raridade = 5
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000018"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000005"),
                            DropWeight = 25,
                            EHeroPrincipal = false,
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000027"),
                            Raridade = 5
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000019"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000005"),
                            DropWeight = 25,
                            EHeroPrincipal = false,
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000028"),
                            Raridade = 5
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000020"),
                            BiomeId = new Guid("b1000000-0000-0000-0000-000000000005"),
                            DropWeight = 20,
                            EHeroPrincipal = false,
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000029"),
                            Raridade = 5
                        });
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Fragmento.Bioma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AndarFim")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AndarInicio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Biomas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000001"),
                            AndarFim = 25,
                            AndarInicio = 1,
                            Descricao = "Uma floresta antiga onde aventureiros escrevem suas primeiras histórias.",
                            Nome = "Floresta de Aelindra",
                            Tag = "Floresta"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000002"),
                            AndarFim = 50,
                            AndarInicio = 26,
                            Descricao = "Ruínas de uma civilização esquecida, repletas de armadilhas e segredos.",
                            Nome = "Ruínas de Valdrek",
                            Tag = "Ruinas"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000003"),
                            AndarFim = 75,
                            AndarInicio = 51,
                            Descricao = "O cume incandescente onde os guerreiros mais duros são forjados.",
                            Nome = "Pico Vulcânico",
                            Tag = "Vulcanico"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000004"),
                            AndarFim = 100,
                            AndarInicio = 76,
                            Descricao = "Um abismo de trevas onde anjos caídos e magos do vazio travam suas guerras eternas.",
                            Nome = "Abismo Sombrio",
                            Tag = "Abismo"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000005"),
                            AndarFim = 125,
                            AndarInicio = 101,
                            Descricao = "O palco final do conflito entre Serafins e Anjos Caídos pelo destino do mundo mortal.",
                            Nome = "Domínio Celestial",
                            Tag = "Celestial"
                        });
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Fragmento.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Arquetipo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiraEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HeroiId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroiId");

                    b.HasIndex("UsuarioId", "Tipo", "Ativo")
                        .IsUnique()
                        .HasFilter("\"Ativo\" = 1");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Fragmento.FragmentoProgresso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Arquetipo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HeroiId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoFragmento")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroiId");

                    b.HasIndex("UsuarioId", "Arquetipo")
                        .IsUnique()
                        .HasFilter("\"Arquetipo\" IS NOT NULL");

                    b.HasIndex("UsuarioId", "HeroiId")
                        .IsUnique()
                        .HasFilter("\"HeroiId\" IS NOT NULL");

                    b.ToTable("FragmentosProgresso");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Fragmento.HeroiConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Arquetipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RaridadeBase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HeroiConfigs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Arquetipo = 0,
                            Nome = "Aldric",
                            RaridadeBase = 5,
                            Titulo = "o Sem-Corrente"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            Arquetipo = 2,
                            Nome = "Yuzara",
                            RaridadeBase = 5,
                            Titulo = "a Tecelã do Destino"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            Arquetipo = 14,
                            Nome = "Thorvald",
                            RaridadeBase = 5,
                            Titulo = "o Arquiteto das Eras"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000004"),
                            Arquetipo = 1,
                            Nome = "Kaen",
                            RaridadeBase = 4
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000005"),
                            Arquetipo = 3,
                            Nome = "Nyra",
                            RaridadeBase = 4
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000006"),
                            Arquetipo = 4,
                            Nome = "Seraph",
                            RaridadeBase = 4
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000007"),
                            Arquetipo = 17,
                            Nome = "Mira",
                            RaridadeBase = 4
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000008"),
                            Arquetipo = 12,
                            Nome = "Grom",
                            RaridadeBase = 4
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000009"),
                            Arquetipo = 13,
                            Nome = "Hana",
                            RaridadeBase = 4
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000001"),
                            Arquetipo = 1,
                            Nome = "Lira",
                            RaridadeBase = 3,
                            Tag = "B1",
                            Titulo = "Flecha Dourada"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000002"),
                            Arquetipo = 7,
                            Nome = "Korin",
                            RaridadeBase = 3,
                            Tag = "B1",
                            Titulo = "Guardã do Bosque"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000003"),
                            Arquetipo = 6,
                            Nome = "Rinzi",
                            RaridadeBase = 4,
                            Tag = "B1",
                            Titulo = "Filha do Mercado"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000004"),
                            Arquetipo = 2,
                            Nome = "Selva",
                            RaridadeBase = 3,
                            Tag = "B1",
                            Titulo = "Filha da Raiz"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000005"),
                            Arquetipo = 7,
                            Nome = "Lune",
                            RaridadeBase = 4,
                            Tag = "B1",
                            Titulo = "Voz da Alcateia"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000006"),
                            Arquetipo = 0,
                            Nome = "Sera",
                            RaridadeBase = 4,
                            Tag = "B1",
                            Titulo = "Caçadora das Neves"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000007"),
                            Arquetipo = 0,
                            Nome = "Igara",
                            RaridadeBase = 4,
                            Tag = "B2",
                            Titulo = "Ruído do Vulcão"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000008"),
                            Arquetipo = 0,
                            Nome = "Varga",
                            RaridadeBase = 4,
                            Tag = "B2",
                            Titulo = "a Corrente Solta"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000009"),
                            Arquetipo = 0,
                            Nome = "Skaara",
                            RaridadeBase = 4,
                            Tag = "B2",
                            Titulo = "Fogo Desperto"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000010"),
                            Arquetipo = 3,
                            Nome = "Velara",
                            RaridadeBase = 5,
                            Tag = "B2",
                            Titulo = "a Sombra sem Nome"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000011"),
                            Arquetipo = 7,
                            Nome = "Nara",
                            RaridadeBase = 4,
                            Tag = "B2",
                            Titulo = "Maestrina Noturna"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000012"),
                            Arquetipo = 2,
                            Nome = "Elisse",
                            RaridadeBase = 4,
                            Tag = "B2",
                            Titulo = "a Ordem Perfeita"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000013"),
                            Arquetipo = 4,
                            Nome = "Draxa",
                            RaridadeBase = 4,
                            Tag = "B3",
                            Titulo = "a Fortaleza Viva"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000014"),
                            Arquetipo = 3,
                            Nome = "Kira",
                            RaridadeBase = 4,
                            Tag = "B3",
                            Titulo = "Lâmina do Crepúsculo"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000015"),
                            Arquetipo = 2,
                            Nome = "Marev",
                            RaridadeBase = 4,
                            Tag = "B3",
                            Titulo = "a Maré Eterna"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000016"),
                            Arquetipo = 2,
                            Nome = "Zara",
                            RaridadeBase = 4,
                            Tag = "B3",
                            Titulo = "a Bruxa do Vazio"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000017"),
                            Arquetipo = 0,
                            Nome = "Valdara",
                            RaridadeBase = 5,
                            Tag = "B3",
                            Titulo = "a Herança Negra"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000018"),
                            Arquetipo = 2,
                            Nome = "Lilith",
                            RaridadeBase = 4,
                            Tag = "B3",
                            Titulo = "Camareira do Caos"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000019"),
                            Arquetipo = 0,
                            Nome = "Zarael",
                            RaridadeBase = 5,
                            Tag = "B4",
                            Titulo = "a Acorrentada"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000020"),
                            Arquetipo = 2,
                            Nome = "Moira",
                            RaridadeBase = 5,
                            Tag = "B4",
                            Titulo = "a Ceifeira"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000021"),
                            Arquetipo = 2,
                            Nome = "Zephirael",
                            RaridadeBase = 4,
                            Tag = "B4",
                            Titulo = "a Tempestade Caída"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000022"),
                            Arquetipo = 4,
                            Nome = "Malachiel",
                            RaridadeBase = 5,
                            Tag = "B4",
                            Titulo = "a Muralha Quebrada"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000023"),
                            Arquetipo = 2,
                            Nome = "Vesper",
                            RaridadeBase = 5,
                            Tag = "B4",
                            Titulo = "o Abismo Vestido"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000024"),
                            Arquetipo = 7,
                            Nome = "Vrael",
                            RaridadeBase = 5,
                            Tag = "B4",
                            Titulo = "a Voz do Vácuo"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000025"),
                            Arquetipo = 4,
                            Nome = "Aelia",
                            RaridadeBase = 5,
                            Tag = "B5",
                            Titulo = "Sentinela do Limiar"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000026"),
                            Arquetipo = 6,
                            Nome = "Elyriel",
                            RaridadeBase = 5,
                            Tag = "B5",
                            Titulo = "a Última Canção"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000027"),
                            Arquetipo = 0,
                            Nome = "Seraphael",
                            RaridadeBase = 5,
                            Tag = "B5",
                            Titulo = "a Chama Corrompida"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000028"),
                            Arquetipo = 5,
                            Nome = "Lumira",
                            RaridadeBase = 5,
                            Tag = "B5",
                            Titulo = "Bênção da Alvorada"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000029"),
                            Arquetipo = 0,
                            Nome = "Aurael",
                            RaridadeBase = 5,
                            Tag = "B5",
                            Titulo = "o Punho do Éden"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000030"),
                            Arquetipo = 3,
                            Nome = "Nyx",
                            RaridadeBase = 5,
                            Tag = "B5",
                            Titulo = "Umbraveil"
                        });
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Fragmento.HeroiDesbloqueado", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HeroiId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DesbloqueadoEm")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId", "HeroiId");

                    b.HasIndex("HeroiId");

                    b.ToTable("HeroisDesbloqueados");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Fragmento.HeroiUnlockConfig", b =>
                {
                    b.Property<Guid>("HeroiId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AndarMarco")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CondicaoDescricao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QuantidadeFragmentos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoUnlock")
                        .HasColumnType("INTEGER");

                    b.HasKey("HeroiId");

                    b.ToTable("HeroiUnlockConfigs");

                    b.HasData(
                        new
                        {
                            HeroiId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            AndarMarco = 30,
                            TipoUnlock = 2
                        },
                        new
                        {
                            HeroiId = new Guid("a1000000-0000-0000-0000-000000000002"),
                            AndarMarco = 60,
                            TipoUnlock = 2
                        },
                        new
                        {
                            HeroiId = new Guid("a1000000-0000-0000-0000-000000000003"),
                            QuantidadeFragmentos = 60,
                            TipoUnlock = 1
                        },
                        new
                        {
                            HeroiId = new Guid("a1000000-0000-0000-0000-000000000004"),
                            AndarMarco = 10,
                            TipoUnlock = 2
                        },
                        new
                        {
                            HeroiId = new Guid("a1000000-0000-0000-0000-000000000006"),
                            QuantidadeFragmentos = 40,
                            TipoUnlock = 1
                        },
                        new
                        {
                            HeroiId = new Guid("a1000000-0000-0000-0000-000000000007"),
                            QuantidadeFragmentos = 35,
                            TipoUnlock = 1
                        },
                        new
                        {
                            HeroiId = new Guid("a1000000-0000-0000-0000-000000000008"),
                            QuantidadeFragmentos = 30,
                            TipoUnlock = 1
                        },
                        new
                        {
                            HeroiId = new Guid("a1000000-0000-0000-0000-000000000005"),
                            CondicaoDescricao = "Completar o andar 15 com a party completa sem nenhum herói ser derrotado",
                            TipoUnlock = 3
                        },
                        new
                        {
                            HeroiId = new Guid("a1000000-0000-0000-0000-000000000009"),
                            CondicaoDescricao = "Ter pelo menos 3 heróis com Humor >= 80 na cidade ao mesmo tempo",
                            TipoUnlock = 3
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000001"),
                            QuantidadeFragmentos = 20,
                            TipoUnlock = 1
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000002"),
                            QuantidadeFragmentos = 20,
                            TipoUnlock = 1
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000003"),
                            AndarMarco = 8,
                            TipoUnlock = 2
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000004"),
                            QuantidadeFragmentos = 25,
                            TipoUnlock = 1
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000005"),
                            QuantidadeFragmentos = 30,
                            TipoUnlock = 1
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000006"),
                            AndarMarco = 20,
                            TipoUnlock = 2
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000007"),
                            QuantidadeFragmentos = 35,
                            TipoUnlock = 1
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000008"),
                            AndarMarco = 26,
                            TipoUnlock = 2
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000009"),
                            QuantidadeFragmentos = 38,
                            TipoUnlock = 1
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000010"),
                            AndarMarco = 36,
                            TipoUnlock = 2
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000011"),
                            QuantidadeFragmentos = 42,
                            TipoUnlock = 1
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000012"),
                            QuantidadeFragmentos = 45,
                            TipoUnlock = 1
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000013"),
                            AndarMarco = 51,
                            TipoUnlock = 2
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000014"),
                            QuantidadeFragmentos = 50,
                            TipoUnlock = 1
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000015"),
                            QuantidadeFragmentos = 52,
                            TipoUnlock = 1
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000016"),
                            AndarMarco = 60,
                            TipoUnlock = 2
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000017"),
                            AndarMarco = 68,
                            TipoUnlock = 2
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000018"),
                            QuantidadeFragmentos = 56,
                            TipoUnlock = 1
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000019"),
                            AndarMarco = 76,
                            TipoUnlock = 2
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000020"),
                            QuantidadeFragmentos = 58,
                            TipoUnlock = 1
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000021"),
                            QuantidadeFragmentos = 60,
                            TipoUnlock = 1
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000022"),
                            AndarMarco = 88,
                            TipoUnlock = 2
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000023"),
                            QuantidadeFragmentos = 62,
                            TipoUnlock = 1
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000024"),
                            CondicaoDescricao = "Completar o Bioma 3 com 3 ou mais Bestiais na mesma party",
                            TipoUnlock = 3
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000025"),
                            AndarMarco = 101,
                            TipoUnlock = 2
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000026"),
                            QuantidadeFragmentos = 65,
                            TipoUnlock = 1
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000027"),
                            AndarMarco = 108,
                            TipoUnlock = 2
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000028"),
                            QuantidadeFragmentos = 68,
                            TipoUnlock = 1
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000029"),
                            QuantidadeFragmentos = 70,
                            TipoUnlock = 1
                        },
                        new
                        {
                            HeroiId = new Guid("a2000000-0000-0000-0000-000000000030"),
                            CondicaoDescricao = "Derrotar o chefe do Andar 120 sem perder nenhum herói na tentativa",
                            TipoUnlock = 3
                        });
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Habilidade", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfissaoVinculada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoHabilidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.HabilidadeBonusAtributos", b =>
                {
                    b.Property<string>("HabilidadeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Atributo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusTipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusValor")
                        .HasColumnType("INTEGER");

                    b.HasKey("HabilidadeId", "Atributo");

                    b.ToTable("HabilidadeBonusAtributos");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Heroi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AndaresConquistados")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Antecedente")
                        .HasColumnType("TEXT");

                    b.Property<int>("Confianca")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Derrotas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoSustento")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Funcao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Historia")
                        .HasColumnType("TEXT");

                    b.Property<int>("Humor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Lealdade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lore")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Personalidade")
                        .HasColumnType("TEXT");

                    b.Property<int>("PontosAtributosDisponiveis")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Profissao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Raca")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Raridade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vitorias")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XP")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Herois");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.HeroiHabilidade", b =>
                {
                    b.Property<Guid>("HeroiId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HabilidadeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaEmTreinamento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XPAtual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XPMaximo")
                        .HasColumnType("INTEGER");

                    b.HasKey("HeroiId", "HabilidadeId");

                    b.HasIndex("HabilidadeId");

                    b.ToTable("HeroiHabilidades");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Inimigo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Habilidades")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TorreAndarId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TorreAndarId");

                    b.ToTable("Inimigo");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaEquipado")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("HeroiEquipadoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ProprietarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Qualidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.ItemBonus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Atributo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemBonus");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NomeModoManual")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.PartyHero", b =>
                {
                    b.Property<Guid>("PartyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HeroiId")
                        .HasColumnType("TEXT");

                    b.HasKey("PartyId", "HeroiId");

                    b.HasIndex("HeroiId");

                    b.ToTable("PartyHeroes");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.PersonagemTrabalhador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CidadeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HeroiId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InicioTrabalho")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResourceNode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.ToTable("PersonagemTrabalhador");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.SlotOcupacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConstrucaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HeroiId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PosicaoSlot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotTipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConstrucaoId");

                    b.ToTable("SlotOcupacoes");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.TorreAndar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DificuldadeBoss")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NivelDificuldade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ObjetivoCumprido")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecompensaQuantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecompensaTipo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TemBoss")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Andares");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Usuario", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AndarMaisAlto")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CidadeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cristais")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Fragmentos")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("HeroisIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Moedas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NivelConta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PergaminhosSecretos")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UltimoLogin")
                        .HasColumnType("TEXT");

                    b.Property<int>("XP")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Auxiliares.HeroiAfinidadeElemental", b =>
                {
                    b.HasOne("LegendsAwaken.Domain.Entities.Heroi", "Heroi")
                        .WithMany("AfinidadeElemental")
                        .HasForeignKey("HeroiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heroi");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Auxiliares.HeroiBonusAtributo", b =>
                {
                    b.HasOne("LegendsAwaken.Domain.Entities.Heroi", "Heroi")
                        .WithMany("BonusAtributos")
                        .HasForeignKey("HeroiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heroi");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Auxiliares.HeroiTag", b =>
                {
                    b.HasOne("LegendsAwaken.Domain.Entities.Heroi", "Heroi")
                        .WithMany("Tags")
                        .HasForeignKey("HeroiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heroi");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Auxiliares.HeroiVinculo", b =>
                {
                    b.HasOne("LegendsAwaken.Domain.Entities.Heroi", "Heroi")
                        .WithMany("VinculosHeroicos")
                        .HasForeignKey("HeroiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heroi");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Cidade", b =>
                {
                    b.OwnsOne("LegendsAwaken.Domain.Entities.Recursos", "Recursos", b1 =>
                        {
                            b1.Property<Guid>("CidadeId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Comida")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Erva")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Madeira")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Ouro")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Pedra")
                                .HasColumnType("INTEGER");

                            b1.HasKey("CidadeId");

                            b1.ToTable("Cidades");

                            b1.WithOwner()
                                .HasForeignKey("CidadeId");
                        });

                    b.Navigation("Recursos")
                        .IsRequired();
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Construcao", b =>
                {
                    b.HasOne("LegendsAwaken.Domain.Entities.Cidade", null)
                        .WithMany("Construcoes")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Fragmento.BiomHeroPool", b =>
                {
                    b.HasOne("LegendsAwaken.Domain.Entities.Fragmento.Bioma", "Bioma")
                        .WithMany("Pool")
                        .HasForeignKey("BiomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegendsAwaken.Domain.Entities.Fragmento.HeroiConfig", "Heroi")
                        .WithMany()
                        .HasForeignKey("HeroiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bioma");

                    b.Navigation("Heroi");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Fragmento.Contrato", b =>
                {
                    b.HasOne("LegendsAwaken.Domain.Entities.Fragmento.HeroiConfig", "Heroi")
                        .WithMany()
                        .HasForeignKey("HeroiId");

                    b.Navigation("Heroi");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Fragmento.FragmentoProgresso", b =>
                {
                    b.HasOne("LegendsAwaken.Domain.Entities.Fragmento.HeroiConfig", "Heroi")
                        .WithMany()
                        .HasForeignKey("HeroiId");

                    b.Navigation("Heroi");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Fragmento.HeroiDesbloqueado", b =>
                {
                    b.HasOne("LegendsAwaken.Domain.Entities.Fragmento.HeroiConfig", "Heroi")
                        .WithMany()
                        .HasForeignKey("HeroiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heroi");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Fragmento.HeroiUnlockConfig", b =>
                {
                    b.HasOne("LegendsAwaken.Domain.Entities.Fragmento.HeroiConfig", "Heroi")
                        .WithMany()
                        .HasForeignKey("HeroiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heroi");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.HabilidadeBonusAtributos", b =>
                {
                    b.HasOne("LegendsAwaken.Domain.Entities.Habilidade", "Habilidade")
                        .WithMany("HabilidadeBonusAtributos")
                        .HasForeignKey("HabilidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidade");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Heroi", b =>
                {
                    b.OwnsOne("LegendsAwaken.Domain.Entities.Equipamentos", "Equipamentos", b1 =>
                        {
                            b1.Property<Guid>("HeroiId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("AcessorioId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("ArmaId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("ArmaduraId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .HasColumnType("INTEGER");

                            b1.HasKey("HeroiId");

                            b1.ToTable("Herois");

                            b1.WithOwner()
                                .HasForeignKey("HeroiId");
                        });

                    b.OwnsOne("LegendsAwaken.Domain.Entities.AtributosBase", "AtributosBase", b1 =>
                        {
                            b1.Property<Guid>("HeroiId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Agilidade")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Forca")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Inteligencia")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Percepcao")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Vitalidade")
                                .HasColumnType("INTEGER");

                            b1.HasKey("HeroiId");

                            b1.ToTable("Herois");

                            b1.WithOwner()
                                .HasForeignKey("HeroiId");
                        });

                    b.OwnsOne("LegendsAwaken.Domain.Entities.AtributosBase", "AtributosDistribuidos", b1 =>
                        {
                            b1.Property<Guid>("HeroiId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Agilidade")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Forca")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Inteligencia")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Percepcao")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Vitalidade")
                                .HasColumnType("INTEGER");

                            b1.HasKey("HeroiId");

                            b1.ToTable("Herois");

                            b1.WithOwner()
                                .HasForeignKey("HeroiId");
                        });

                    b.OwnsOne("LegendsAwaken.Domain.Entities.StatusCombate", "Status", b1 =>
                        {
                            b1.Property<Guid>("HeroiId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("ManaAtual")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ManaMaxima")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("VidaAtual")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("VidaMaxima")
                                .HasColumnType("INTEGER");

                            b1.HasKey("HeroiId");

                            b1.ToTable("Herois");

                            b1.WithOwner()
                                .HasForeignKey("HeroiId");
                        });

                    b.OwnsOne("LegendsAwaken.Domain.Entities.Treinamento", "Treinamento", b1 =>
                        {
                            b1.Property<Guid>("HeroiId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Fim")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Inicio")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ResultadoEsperado")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("UltimoTreino")
                                .HasColumnType("TEXT");

                            b1.HasKey("HeroiId");

                            b1.ToTable("Herois");

                            b1.WithOwner()
                                .HasForeignKey("HeroiId");
                        });

                    b.Navigation("AtributosBase")
                        .IsRequired();

                    b.Navigation("AtributosDistribuidos")
                        .IsRequired();

                    b.Navigation("Equipamentos")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();

                    b.Navigation("Treinamento");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.HeroiHabilidade", b =>
                {
                    b.HasOne("LegendsAwaken.Domain.Entities.Habilidade", "Habilidade")
                        .WithMany()
                        .HasForeignKey("HabilidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegendsAwaken.Domain.Entities.Heroi", "Heroi")
                        .WithMany("Habilidades")
                        .HasForeignKey("HeroiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidade");

                    b.Navigation("Heroi");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Inimigo", b =>
                {
                    b.HasOne("LegendsAwaken.Domain.Entities.TorreAndar", null)
                        .WithMany("Inimigos")
                        .HasForeignKey("TorreAndarId");

                    b.OwnsOne("LegendsAwaken.Domain.Entities.AtributosBase", "Atributos", b1 =>
                        {
                            b1.Property<Guid>("InimigoId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Agilidade")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Forca")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Inteligencia")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Percepcao")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Vitalidade")
                                .HasColumnType("INTEGER");

                            b1.HasKey("InimigoId");

                            b1.ToTable("Inimigo");

                            b1.WithOwner()
                                .HasForeignKey("InimigoId");
                        });

                    b.Navigation("Atributos")
                        .IsRequired();
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.ItemBonus", b =>
                {
                    b.HasOne("LegendsAwaken.Domain.Entities.Item", null)
                        .WithMany("Bonus")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.PartyHero", b =>
                {
                    b.HasOne("LegendsAwaken.Domain.Entities.Heroi", "Heroi")
                        .WithMany()
                        .HasForeignKey("HeroiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegendsAwaken.Domain.Entities.Party", "Party")
                        .WithMany("Membros")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heroi");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.PersonagemTrabalhador", b =>
                {
                    b.HasOne("LegendsAwaken.Domain.Entities.Cidade", null)
                        .WithMany("Trabalhadores")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.SlotOcupacao", b =>
                {
                    b.HasOne("LegendsAwaken.Domain.Entities.Construcao", null)
                        .WithMany()
                        .HasForeignKey("ConstrucaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Cidade", b =>
                {
                    b.Navigation("Construcoes");

                    b.Navigation("Trabalhadores");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Fragmento.Bioma", b =>
                {
                    b.Navigation("Pool");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Habilidade", b =>
                {
                    b.Navigation("HabilidadeBonusAtributos");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Heroi", b =>
                {
                    b.Navigation("AfinidadeElemental");

                    b.Navigation("BonusAtributos");

                    b.Navigation("Habilidades");

                    b.Navigation("Tags");

                    b.Navigation("VinculosHeroicos");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Item", b =>
                {
                    b.Navigation("Bonus");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.Party", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("LegendsAwaken.Domain.Entities.TorreAndar", b =>
                {
                    b.Navigation("Inimigos");
                });
#pragma warning restore 612, 618
        }
    }
}
